on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - 'base-r/**'
      - 'rstudio-arm/**'
      - '.github/workflows/arm.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'base-r/**'
      - 'rstudio-arm/**'
      - '.github/workflows/arm.yml'
  schedule:
    - cron: '0 18 * * 0' # run Sundays at 18

name: Publish Docker image, both arm and amd

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registries:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: base-r}
          - {name: rstudio-arm}
    name: ${{ matrix.config.name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: "Dockerfile"
      - name: Prepare tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: rapporteket/${{ matrix.config.name }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=ref,event=branch
            type=schedule,pattern=weekly
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: "${{ matrix.image }}/Dockerfile"
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.image }}/.
          file: ./${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            GITHUB_PAT=${{ secrets.GH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
